AllCops:
  RunRailsCops: true

Metrics/LineLength:
  Max: 200

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Most readable form.
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Mixing the styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys